version: "3.9"

volumes:
    db-store:

services:
  nginx:
    image: nginx:1.25.1-alpine3.17
    container_name: nginx
    volumes:
      - ./src/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    depends_on:
      - php

  php:
    build: ./src/docker/php
    container_name: php
    volumes:
      - ./src/:/var/www
      - ./docker/php/conf.d/overrides.ini:/usr/local/etc/php/conf.d/overrides.ini
    depends_on:
      - db

  db:
    platform: linux/x86_64
    build: ./src/docker/db
    container_name: db
    volumes:
      - ./src/docker/db/initdb.d:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
